# Generated by Django 4.1.7 on 2023-03-22 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdvertisementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=5000)),
                ("price", models.IntegerField()),
                ("address", models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "advertisement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ThingsCrossing.advertisementmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacteristicModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("characteristic_value", models.CharField(max_length=255)),
                ("characteristic_name", models.CharField(max_length=255)),
                (
                    "advertisement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ThingsCrossing.advertisementmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvertisementPicturesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "advertisement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ThingsCrossing.advertisementmodel",
                    ),
                ),
            ],
        ),
    ]
