# Generated by Django 4.1.7 on 2023-03-22 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdvertisementPicturesModel",
            new_name="PicturesModel",
        ),
    ]
