# Generated by Django 4.1.7 on 2023-03-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0002_rename_advertisementpicturesmodel_picturesmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picturesmodel",
            old_name="url",
            new_name="image_url",
        ),
    ]
