# Generated by Django 4.1.7 on 2023-03-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0003_rename_url_picturesmodel_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picturesmodel",
            name="advertisement_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="ThingsCrossing.advertisementmodel",
            ),
        ),
    ]
