# Generated by Django 4.1.7 on 2023-03-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0004_alter_picturesmodel_advertisement_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdvertisementModel",
            new_name="Advertisement",
        ),
        migrations.RenameModel(
            old_name="CharacteristicModel",
            new_name="Characteristic",
        ),
        migrations.RenameModel(
            old_name="ExchangeModel",
            new_name="Exchange",
        ),
        migrations.RenameModel(
            old_name="PicturesModel",
            new_name="Pictures",
        ),
    ]
