# Generated by Django 4.1.7 on 2023-03-23 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0005_rename_advertisementmodel_advertisement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advertisement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
