# Generated by Django 4.2 on 2023-05-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThingsCrossing', '0005_room_last_message_datetime_alter_participant_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='ThingsCrossing.userprofile'),
        ),
    ]
