# Generated by Django 4.1.7 on 2023-03-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0006_advertisement_created_at_advertisement_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characteristic",
            old_name="characteristic_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="characteristic",
            old_name="characteristic_value",
            new_name="value",
        ),
        migrations.AlterField(
            model_name="characteristic",
            name="advertisement_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristics",
                to="ThingsCrossing.advertisement",
            ),
        ),
        migrations.AlterField(
            model_name="exchange",
            name="advertisement_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchange",
                to="ThingsCrossing.advertisement",
            ),
        ),
        migrations.AlterField(
            model_name="pictures",
            name="advertisement_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_urls",
                to="ThingsCrossing.advertisement",
            ),
        ),
    ]
