# Generated by Django 4.2 on 2023-05-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThingsCrossing', '0006_alter_message_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_message_datetime',
        ),
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message', to='ThingsCrossing.message'),
        ),
    ]
