# Generated by Django 4.1.7 on 2023-03-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ThingsCrossing",
            "0007_rename_characteristic_name_characteristic_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="price",
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "currency_code",
                    models.CharField(
                        choices=[("RUB", "Rubles"), ("USD", "Dollars")], max_length=255
                    ),
                ),
                (
                    "advertisement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="ThingsCrossing.advertisement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "advertisement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="ThingsCrossing.advertisement",
                    ),
                ),
            ],
        ),
    ]
