# Generated by Django 4.1.7 on 2023-03-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0008_remove_advertisement_price_price_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pictures",
            new_name="Picture",
        ),
        migrations.AlterField(
            model_name="price",
            name="advertisement_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="ThingsCrossing.advertisement",
            ),
        ),
    ]
