# Generated by Django 4.1.7 on 2023-03-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0009_rename_pictures_picture_alter_price_advertisement_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="price",
            unique_together={("currency_code", "advertisement_id")},
        ),
    ]
