# Generated by Django 4.1.7 on 2023-03-26 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0010_alter_price_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="value",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1000000000000000),
                ]
            ),
        ),
    ]
