# Generated by Django 4.1.7 on 2023-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0011_alter_price_value"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                check=models.Q(("value__gte", 0.0), ("value__lte", 1000000000000000)),
                name="check_price_value_range",
            ),
        ),
    ]
