# Generated by Django 4.1.7 on 2023-04-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0012_price_check_price_value_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="image_url",
        ),
        migrations.AddField(
            model_name="picture",
            name="image",
            field=models.ImageField(
                default="http://sadf",
                upload_to="advertisement_pictures",
                verbose_name="Картинки",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="picture",
            name="advertisement_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="ThingsCrossing.advertisement",
            ),
        ),
    ]
