# Generated by Django 4.1.7 on 2023-04-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0013_remove_picture_image_url_picture_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="category",
            new_name="name",
        ),
    ]
