# Generated by Django 4.1.7 on 2023-04-02 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0014_alter_category_options_rename_category_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="characteristic",
            old_name="advertisement_id",
            new_name="advertisement",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="advertisement_id",
            new_name="advertisement",
        ),
        migrations.RenameField(
            model_name="price",
            old_name="advertisement_id",
            new_name="advertisement",
        ),
        migrations.RemoveField(
            model_name="exchange",
            name="advertisement_id",
        ),
        migrations.AddField(
            model_name="exchange",
            name="advertisement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchanges",
                to="ThingsCrossing.advertisement",
            ),
            preserve_default=False,
        ),
    ]
