# Generated by Django 4.1.7 on 2023-04-02 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "ThingsCrossing",
            "0015_rename_advertisement_id_characteristic_advertisement_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="advertisement_id",
            new_name="advertisement",
        ),
        migrations.AlterField(
            model_name="picture",
            name="advertisement",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="ThingsCrossing.advertisement",
            ),
        ),
    ]
