# Generated by Django 4.1.7 on 2023-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ThingsCrossing", "0017_alter_picture_advertisement"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="in_search",
            field=models.BooleanField(
                default=False, verbose_name="Отображать в поиске"
            ),
        ),
    ]
