# Generated by Django 4.2 on 2023-05-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThingsCrossing', '0018_advertisement_in_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='in_search',
            field=models.BooleanField(default=True, verbose_name='Отображать в поиске'),
        ),
    ]
